# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373

# STRIPE see stripe.rb
#  'Figaro will take care of converting these key-value pairs to ENV variables locally.' -> how so?
STRIPE_SECRET_KEY: sk_test_19aGdRUUE2cj2FbuTIHf75vn
STRIPE_PUBLISHABLE_KEY: pk_test_SsVb0YpPEG2UjWRa6xOiy8Aw

#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
